name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Flake Check
        run: nix flake check --impure

  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    strategy:
      matrix:
        loader:
          - fabric
          - neoforge
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.11.1'

      # Verify Gradle version
      - name: Verify Gradle version
        run: ./gradlew --version

      # Build the project using the loader matrix
      - name: Build
        run: ./gradlew ${{ matrix.loader }}:build

      # Upload the built JAR artifacts
      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ matrix.loader }}
          overwrite: true
          path: |
            ${{ matrix.loader }}/build/libs/*.jar
            !${{ matrix.loader }}/build/libs/*-sources.jar
            !${{ matrix.loader }}/build/libs/*-shadow.jar
